[tool.setuptools_scm]
write_to = "PyUIRender/_version.py"
version_scheme = "release-branch-semver"  # Prevents dev versions in tags
local_scheme = "no-local-version"        # Removes local identifiers